export default [
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
  {
    id: 315162,
    title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    posterHorizontal: "/faXT8V80JRhnArTAeYXz0Eutpv9.jpg",
    voteAverage: 8.6,
    type: "movie",
    videoUrl: "tHb7WlgyaUc",
    similar: [
      {
        id: 920,
        title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster: "/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg",
        posterHorizontal: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        voteAverage: 6.905,
        type: "movie",
        videoUrl: "SbXIj2T-_uk",
      },
      {
        id: 943,
        title: "Lethal Weapon 3",
        overview:
          "Archetypal buddy cops Riggs and Murtaugh are back for another round of high-stakes action, this time setting their collective sights on bringing down a former Los Angeles police lieutenant turned black market weapons dealer. Lorna Cole joins as the beautiful yet hardnosed internal affairs sergeant who catches Riggs's eye.",
        poster: "/8FnOudDHPOY7MFJnvQMR1qpuyek.jpg",
        posterHorizontal: "/kmt9XmhmX36sJduuDVFlTgEWh9U.jpg",
        voteAverage: 6.687,
        type: "movie",
        videoUrl: "g3JHIZYdVNk",
      },
      {
        id: 153,
        title: "Lost in Translation",
        overview:
          "Two lost souls visiting Tokyo -- the young, neglected wife of a photographer and a washed-up movie star shooting a TV commercial -- find an odd solace and pensive freedom to be real in each other's company, away from their lives in America.",
        poster: "/wkSzJs7oMf8MIr9CQVICsvRfwA7.jpg",
        posterHorizontal: "/45He7gApNQyDbqCDjxew9BnHzjf.jpg",
        voteAverage: 7.389,
        type: "movie",
        videoUrl: "1s4YQqnbnM8",
      },
      {
        id: 411,
        title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
        overview:
          "Siblings Lucy, Edmund, Susan and Peter step through a magical wardrobe and find the land of Narnia. There, they discover a charming, once peaceful kingdom that has been plunged into eternal winter by the evil White Witch, Jadis. Aided by the wise and magnificent lion, Aslan, the children lead Narnia into a spectacular, climactic battle to be free of the Witch's glacial powers forever.",
        poster: "/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
        posterHorizontal: "/sKK5bbQm15jzbMRwCJmPBbv9trN.jpg",
        voteAverage: 7.115,
        type: "movie",
        videoUrl: "3mKPrxjwF7A",
      },
      {
        id: 12,
        title: "Finding Nemo",
        overview:
          "Nemo, an adventurous young clownfish, is unexpectedly taken from his Great Barrier Reef home to a dentist's office aquarium. It's up to his worrisome father Marlin and a friendly but forgetful fish Dory to bring Nemo home -- meeting vegetarian sharks, surfer dude turtles, hypnotic jellyfish, hungry seagulls, and more along the way.",
        poster: "/7DPFmp0q5RC1p582SdIuZ4KBF2.jpg",
        posterHorizontal: "/yzqaKAhglTrkeOfuIXYYArf0WnA.jpg",
        voteAverage: 7.823,
        type: "movie",
        videoUrl: "ZS_8btMjx2U",
      },
      {
        id: 22,
        title: "Pirates of the Caribbean: The Curse of the Black Pearl",
        overview:
          "Jack Sparrow, a freewheeling 18th-century pirate, quarrels with a rival pirate bent on pillaging Port Royal. When the governor's daughter is kidnapped, Sparrow decides to help the girl's love save her.",
        poster: "/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
        posterHorizontal: "/uRNgkJSkNBFbbn9fPsEjDIy8Sh3.jpg",
        voteAverage: 7.782,
        type: "movie",
        videoUrl: "naQr0uTrH_s",
      },
    ],
  },
];
